caos_monopoly_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CaosMonopolyBundle:Default:index }

CaosMonopolyBundle_usuario:
    resource: "@CaosMonopolyBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario
    
CaosMonopolyBundle_personaje:
    resource: "@CaosMonopolyBundle/Resources/config/routing/personaje.yml"
    prefix:   /personaje
    
CaosMonopolyBundle_partida:
    resource: "@CaosMonopolyBundle/Resources/config/routing/partida.yml"
    prefix:   /partida
    
CaosMonopolyBundle_jugador:
    resource: "@CaosMonopolyBundle/Resources/config/routing/jugador.yml"
    prefix:   /jugador
    
CaosMonopolyBundle_casilla:
    resource: "@CaosMonopolyBundle/Resources/config/routing/casilla.yml"
    prefix:   /casilla
    
CaosMonopolyBundle_posesioncasilla:
    resource: "@CaosMonopolyBundle/Resources/config/routing/posesioncasilla.yml"
    prefix:   /posesioncasilla
    
CaosMonopolyBundle_posesiontarjeta:
    resource: "@CaosMonopolyBundle/Resources/config/routing/posesiontarjeta.yml"
    prefix:   /posesiontarjeta