Partida:
    type: entity
    table: partida
    indexes:
        id_jugador_turno:
            columns:
                - id_jugador_turno
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaInicio:
            type: date
            nullable: false
            comment: ''
            column: fecha_inicio
        boteComun:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: bote_comun
        token:
            type: string
            length: 32
            nullable: false
            comment: ''
            column: token
        estado:
            type: string
            length: 30
            nullable: false
            comment: ''
            column: estado
    manyToOne:
        idJugadorTurno:
            nullable: true;
            targetEntity: Jugador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_jugador_turno:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
