Tarjeta:
    type: entity
    table: tarjeta
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: string
            nullable: false
            length: 300
            fixed: false
            comment: ''
        respuestas:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
        beneficio:
            type: integer
            nullable: true
            fixed: false
            comment: ''
        penalizacion:
            type: integer
            nullable: true
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
