partida:
    pattern:  /
    defaults: { _controller: "CaosMonopolyBundle:Partida:index" }

partida_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaosMonopolyBundle:Partida:show" }

partida_enEspera:
    pattern:  /partidasEnEspera
    defaults: { _controller: "CaosMonopolyBundle:Partida:partidasEnEspera" }

partida_new:
    pattern:  /new
    defaults: { _controller: "CaosMonopolyBundle:Partida:new" }
    
partida_crear:
    pattern:  /crear
    defaults: { _controller: "CaosMonopolyBundle:Partida:crear" }

partida_empezar:
    pattern:  /empezar/{id}
    defaults: { _controller: "CaosMonopolyBundle:Partida:empezar" }

partida_create:
    pattern:  /create
    defaults: { _controller: "CaosMonopolyBundle:Partida:create" }
    requirements: { _method: post }

partida_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaosMonopolyBundle:Partida:edit" }

partida_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaosMonopolyBundle:Partida:update" }
    requirements: { _method: post|put }

partida_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaosMonopolyBundle:Partida:delete" }
    requirements: { _method: post|delete }
    
partida_crearPartida:
    pattern: /crearPartida
    defaults: { _controller: "CaosMonopolyBundle:Partida:crearPartida" }
