posesiontarjeta:
    pattern:  /
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:index" }

posesiontarjeta_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:show" }

posesiontarjeta_new:
    pattern:  /new
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:new" }

posesiontarjeta_create:
    pattern:  /create
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:create" }
    requirements: { _method: post }

posesiontarjeta_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:edit" }

posesiontarjeta_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:update" }
    requirements: { _method: post|put }

posesiontarjeta_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaosMonopolyBundle:PosesionTarjeta:delete" }
    requirements: { _method: post|delete }
