usuario:
    pattern:  /
    defaults: { _controller: "CaosMonopolyBundle:Usuario:index" }

usuario_show:
    pattern:  /{id}/show
    defaults: { _controller: "CaosMonopolyBundle:Usuario:show" }

usuario_new:
    pattern:  /new
    defaults: { _controller: "CaosMonopolyBundle:Usuario:new" }

usuario_create:
    pattern:  /create
    defaults: { _controller: "CaosMonopolyBundle:Usuario:create" }
    requirements: { _method: post }

usuario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CaosMonopolyBundle:Usuario:edit" }

usuario_update:
    pattern:  /{id}/update
    defaults: { _controller: "CaosMonopolyBundle:Usuario:update" }
    requirements: { _method: post|put }

usuario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CaosMonopolyBundle:Usuario:delete" }
    requirements: { _method: post|delete }

usuario_autenticado:
    pattern: /autenticado
    defaults: { _controller: "CaosMonopolyBundle:Usuario:estaAutenticado" }

usuario_login:
    pattern: /login
    defaults: { _controller: "CaosMonopolyBundle:Usuario:login" }
    
usuario_crear:
    pattern: /crear
    defaults: { _controller: "CaosMonopolyBundle:Usuario:crearUsuario"}