Caos\MonopolyBundle\Entity\PosesionTarjeta:
    type: entity
    table: posesion_tarjeta
    indexes:
        id_jugador:
            columns:
                - id_jugador
        id_tarjeta:
            columns:
                - id_tarjeta
        id_partida:
            columns:
                - id_partida
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        beneficio:
            type: string
            nullable: false
            length: 300
            fixed: false
            comment: ''
    manyToOne:
        idPartida:
            targetEntity: Partida
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_partida:
                    referencedColumnName: id
            orphanRemoval: false
        idTarjeta:
            targetEntity: Tarjeta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tarjeta:
                    referencedColumnName: id
            orphanRemoval: false
        idJugador:
            targetEntity: Jugador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_jugador:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
