Caos\MonopolyBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 35
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        partidasJugadas:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: partidas_jugadas
        partidasGanadas:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: partidas_ganadas
        estado:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        rol:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
