<?php

namespace Caos\MonopolyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CasillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasillaRepository extends EntityRepository
{
    
    public function obtenerTodos(){
        
        $casillas = $this->getEntityManager()->createQueryBuilder()
                ->select("c")
                ->from("CaosMonopolyBundle:Casilla","c")
                ->getQuery()
                ->getArrayResult();
        
        return $casillas;
        
    }
    
    public function obtenerPorId($id){
        
        $casilla = $this->getEntityManager()->createQueryBuilder()
                ->select("c")
                ->from("CaosMonopolyBundle:Casilla","c")
                ->where("c.id = $id")
                ->getQuery()
                ->getArrayResult();
        
        return $casilla;
        
    }
    
}
