<?php

namespace Caos\MonopolyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorRepository extends EntityRepository {

    public function obtenerTodos() {

        $jugadores = $this->getEntityManager()->createQueryBuilder()
                ->select("j, per, usu, par")
                ->from("CaosMonopolyBundle:Jugador", "j")
                ->join("j.personaje","per")
                ->join("j.usuario","usu")
                ->join("j.partida","par")
                ->getQuery()
                ->getArrayResult();
        
        return $jugadores;
        
    }

    public function obtenerPorId($id) {

        $jugador = $this->getEntityManager()->createQueryBuilder()
                ->select("j, per, usu, par")
                ->from("CaosMonopolyBundle:Jugador", "j")
                ->join("j.personaje","per")
                ->join("j.usuario","usu")
                ->join("j.partida","par")
                ->where("j.id = " . $id)
                ->getQuery()
                ->getArrayResult();

        return $jugador;
    }

    public function obtenerPorUsuario($id){
        
        $jugadores = $this->getEntityManager()->createQueryBuilder()
                ->select("j, per, par")
                ->from("CaosMonopolyBundle:Jugador", "j")
                ->join("j.personaje","per")
                ->join("j.partida","par")
                ->where("j.usuario = ".$id)
                ->getQuery()
                ->getArrayResult();

        return $jugadores;
        
    }
    
    public function obtenerPorPartida($id){
        
        $jugadores = $this->getEntityManager()->createQueryBuilder()
                ->select("j, per, usu")
                ->from("CaosMonopolyBundle:Jugador", "j")
                ->join("j.personaje","per")
                ->join("j.usuario","usu")
                ->where("j.partida = ".$id)
                ->getQuery()
                ->getResult();

        return $jugadores;
        
    }
    
}
