<?php

namespace Caos\MonopolyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PosesionCasillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosesionCasillaRepository extends EntityRepository
{
    
    function comprobarPosesiones($idJugador, $idPartida){
        $posesiones = $this->getEntityManager()->createQueryBuilder()
                ->select("pc, c")
                ->from("CaosMonopolyBundle:PosesionCasilla", "pc")
                ->join("pc.idCasilla","c")
                ->where("pc.idJugador = " . $idJugador)
                ->andWhere("pc.idPartida = " . $idPartida)
                ->getQuery()
                ->getArrayResult();
        
        return $posesiones;
    }
    
}
