<?php

namespace Caos\MonopolyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PosesionCasillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosesionCasillaRepository extends EntityRepository
{
    
    function comprobarPosesiones($idCasilla, $idPartida){
        $poseedor = $this->getEntityManager()->createQueryBuilder()
                ->select("pc")
                ->from("CaosMonopolyBundle:PosesionCasilla", "pc")
                ->where("pc.idCasilla = " . $idCasilla)
                ->andWhere("pc.idPartida = " . $idPartida)
                ->getQuery()
                ->getArrayResult();
        
        return $poseedor;
    }
    
    /**
     * Con este método obtienes todas las posesiones que tiene el jugador en una partida
     * 
     * @param type $idPartida
     *      el id de la partida de la que se quieren obtener los datos
     * @param type $idUsuario
     *      el id del jugador del que se quieren obtener los datos
     * @return type {array}
     *      array con las casillas que tiene el jugador en la partida
     * 
     */
    function obtenerTodasPosesiones($idPartida, $idUsuario) {
        $casillas = $this->getEntityManager()->createQueryBuilder()
                ->select("pc")
                ->from("CaosMonopolyBundle:PosesionCasilla", "pc")
                ->join("pc.idJugador", "j")
                ->where("j.idPartida = " . $idPartida)
                ->andWhere("j.idUsuario = " . $idUsuario)
                ->getQuery()
                ->getArrayResult();
                
        return $casillas;                
    }
    
}
