<?php

namespace Caos\MonopolyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PosesionCasillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosesionCasillaRepository extends EntityRepository
{
    
    function comprobarPosesiones($idCasilla, $idPartida){
        $poseedor = $this->getEntityManager()->createQueryBuilder()
                ->select("pc")
                ->from("CaosMonopolyBundle:PosesionCasilla", "pc")
                ->where("pc.idCasilla = " . $idCasilla)
                ->andWhere("pc.idPartida = " . $idPartida)
                ->getQuery()
                ->getArrayResult();
        
        return $poseedor;
    }
    
}
